use std::fs;
use std::io::{self, Read};

use camino::{Utf8Path, Utf8PathBuf};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tiny_keccak::{Hasher, Keccak};

pub const GENERATED_HEADER: &str = "// GENERATED by tama; do not edit.";

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("I/O error at {path}: {source}")]
    Io {
        path: Utf8PathBuf,
        #[source]
        source: io::Error,
    },
    #[error("could not find Tama project root from {0}")]
    ProjectRootNotFound(Utf8PathBuf),
    #[error("path is not valid UTF-8: {0}")]
    NonUtf8Path(String),
    #[error("refusing to overwrite hand-edited generated file: {0}")]
    GeneratedFileModified(Utf8PathBuf),
    #[error("{0}")]
    Message(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalFailure {
    pub program: String,
    pub args: Vec<String>,
    pub status: Option<i32>,
    pub stderr: String,
}

impl ExternalFailure {
    pub fn message(&self) -> String {
        let code = self
            .status
            .map(|status| status.to_string())
            .unwrap_or_else(|| "terminated by signal".to_string());
        format!(
            "`{} {}` failed with status {}{}",
            self.program,
            self.args.join(" "),
            code,
            if self.stderr.trim().is_empty() {
                String::new()
            } else {
                format!(": {}", self.stderr.trim())
            }
        )
    }
}

pub fn io_error(path: impl Into<Utf8PathBuf>, source: io::Error) -> Error {
    Error::Io {
        path: path.into(),
        source,
    }
}

pub fn read_to_string(path: &Utf8Path) -> Result<String> {
    fs::read_to_string(path).map_err(|source| io_error(path.to_owned(), source))
}

pub fn write_string(path: &Utf8Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| io_error(parent.to_owned(), source))?;
    }
    fs::write(path, contents).map_err(|source| io_error(path.to_owned(), source))
}

pub fn find_project_root(start: &Utf8Path) -> Result<Utf8PathBuf> {
    let mut cursor = if start.is_file() {
        start.parent().unwrap_or(start).to_owned()
    } else {
        start.to_owned()
    };

    loop {
        if cursor.join("tama.toml").is_file() {
            return Ok(cursor);
        }
        if !cursor.pop() {
            return Err(Error::ProjectRootNotFound(start.to_owned()));
        }
    }
}

pub fn artifact_path(root: &Utf8Path, kind: &str, contract: &str, extension: &str) -> Utf8PathBuf {
    root.join("artifacts")
        .join(kind)
        .join(format!("{contract}.{extension}"))
}

pub fn keccak256(input: &[u8]) -> [u8; 32] {
    let mut keccak = Keccak::v256();
    let mut output = [0u8; 32];
    keccak.update(input);
    keccak.finalize(&mut output);
    output
}

pub fn function_selector(signature: &str) -> String {
    let hash = keccak256(signature.as_bytes());
    format!("0x{}", hex::encode(&hash[..4]))
}

pub fn error_selector(signature: &str) -> String {
    function_selector(signature)
}

pub fn event_topic(signature: &str) -> String {
    format!("0x{}", hex::encode(keccak256(signature.as_bytes())))
}

pub fn sha256_bytes(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

pub fn sha256_file(path: &Utf8Path) -> Result<String> {
    let mut file = fs::File::open(path).map_err(|source| io_error(path.to_owned(), source))?;
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 8192];
    loop {
        let read = file
            .read(&mut buf)
            .map_err(|source| io_error(path.to_owned(), source))?;
        if read == 0 {
            break;
        }
        hasher.update(&buf[..read]);
    }
    Ok(hex::encode(hasher.finalize()))
}

pub fn has_generated_header(path: &Utf8Path) -> Result<bool> {
    if !path.exists() {
        return Ok(true);
    }
    let contents = read_to_string(path)?;
    Ok(contents.lines().next() == Some(GENERATED_HEADER))
}

pub fn ensure_generated_overwrite_allowed(path: &Utf8Path) -> Result<()> {
    if has_generated_header(path)? {
        Ok(())
    } else {
        Err(Error::GeneratedFileModified(path.to_owned()))
    }
}

pub fn write_generated(path: &Utf8Path, body: &str) -> Result<()> {
    ensure_generated_overwrite_allowed(path)?;
    let mut contents = String::with_capacity(GENERATED_HEADER.len() + body.len() + 2);
    contents.push_str(GENERATED_HEADER);
    contents.push('\n');
    contents.push_str(body);
    write_string(path, &contents)
}

pub fn init_logging(json: bool, passthrough: bool) {
    if passthrough {
        return;
    }

    let env_filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));
    let builder = tracing_subscriber::fmt()
        .with_env_filter(env_filter)
        .with_writer(io::stderr);

    let result = if json {
        builder.json().try_init()
    } else {
        builder.try_init()
    };
    let _ = result;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_selector_vector() {
        assert_eq!(function_selector("transfer(address,uint256)"), "0xa9059cbb");
    }

    #[test]
    fn known_topic_vector() {
        assert_eq!(
            event_topic("Transfer(address,address,uint256)"),
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
        );
    }

    #[test]
    fn empty_sha256_vector() {
        assert_eq!(
            sha256_bytes(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn generated_file_policy_refuses_hand_edits() {
        let dir = tempfile::tempdir().unwrap();
        let path = Utf8PathBuf::from_path_buf(dir.path().join("Bridge.sol")).unwrap();
        write_string(&path, "// user file\n").unwrap();
        let err = ensure_generated_overwrite_allowed(&path).unwrap_err();
        assert!(matches!(err, Error::GeneratedFileModified(_)));
    }

    #[test]
    fn generated_file_policy_accepts_header() {
        let dir = tempfile::tempdir().unwrap();
        let path = Utf8PathBuf::from_path_buf(dir.path().join("Bridge.sol")).unwrap();
        write_generated(&path, "pragma solidity ^0.8.20;\n").unwrap();
        write_generated(&path, "pragma solidity ^0.8.20;\n").unwrap();
    }
}
