[package]
name = "tama-audit"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
camino.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
tama-common = { path = "../tama-common" }
tama-config = { path = "../tama-config" }
tama-manifest = { path = "../tama-manifest" }
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
